apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset
spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        tier: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
  replicas: 2
  selector:
    matchLabels:
      tier: nginx
