apiVersion: batch/v1
kind: CronJob
metadata:
  name: myjob
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      completions: 3 # no of pods to be run (sequentially by default)
      parallelism: 3 # no of pods to run parallel
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure # Never
          